- name: variables
  hosts: local
  connection: local
  vars:
    ENVIRONMENT: dev
  tasks:
  - name: Use local varialbes
    ansible.builtin.debug:
      msg: "I'm using local varialbes i.e., {{ ENVIRONMENT }}"