- name: variables
  hosts: local
  connection: local
  vars:
    environment: dev
  tasks:
  - name: Use local varialbes
    ansible.builtin.debug:
      msg: "echo I'm using local varialbes i.e., {{ environment }}"